require: rubocop-rails

AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - vendor/**/*
    - tmp/**/*
    - config/**/*
    - bin/**/*
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
